### ISSUE TITLE
Google Docs

### ISSUE THREAD

**Issue by slayernominee** [cyfung1031/userscript-supports#17]
If copy is disabled in google docs it still doesnt work

**Comment by slayernominee** [comment]
the context menu only says as option save image

**Comment by cyfung1031** [comment]
You means "Selection and Copying Restorer (Universal)" right?

added `// @exclude             https://docs.google.com/*`
should exclude Google Docs now.

**Comment by slayernominee** [comment]
yep, now it doesnt give me the image context menu :)
