### ISSUE TITLE
Documentation for "youtube-video-resize-fix"

### ISSUE THREAD

**Issue by D-Rekk** [cyfung1031/userscript-supports#19]
Hi @cyfung1031 👋
I'm a contributor to a YouTube extension ([ImprovedTube](https://github.com/ImprovedTube)) and some months ago I developed a feature to swap the comments and videos sections.
![May-27-2023 12-49-11](https://github.com/cyfung1031/userscript-supports/assets/46907875/08d8473c-d099-4954-a780-426b2c18aabf)

I encountered an annoying bug that made the video appear smaller than the player itself for whatever reason so I did _a pretty rudimental code_ (Observers and inline width)
 
I'm now using your neat script instead of my temporary solution and I have to admit it's working well. I'm asking if you could add documentation of the script or a brief explanation. As far as I understand this allows the YouTube player to trigger resizeEvent by reading the values of the changed CSS instead of the native one.
Also, if you don't mind, let's connect on Discord 🥹 (I'm **D_Rekk** there)

**Comment by cyfung1031** [comment]
@D-Rekk  I don't use Discord sorry.

There are two methods provided by the `ytd-watch-flexy`'s controller.

* `calculateNormalPlayerSize_`
* `calculateCurrentPlayerSize_`

They will give the sizes (width & height as a array) for the player element in normal mode and theater mode.

## What this script does

### Resize the player whenever there is resize of player container, video loaded, chatroom expand/collapse, etc.
### Change the implementation of `calculateNormalPlayerSize_` and `calculateCurrentPlayerSize_`

## Why it is necessary
### If you just change the size of the player, by CSS or whatever, the progress control bar will not be sized correctly.

**Comment by cyfung1031** [comment]
You better check the js implementation in `youtube/js&css/web-accessible/functions.js` of ImprovedYouTube.
For example, `calculateNormalPlayerSize_ = calculateCurrentPlayerSize_` might cause issues in theater mode.

**Comment by D-Rekk** [comment]
> ## Why it is necessary
> * If you just change the size of the player, by CSS or whatever, the progress control bar will not be sized correctly.

This is one of the problems I was dealing with. The video itself would resize automatically with some CSS, but the controlBar would not increase (or shrink) its size accordingly. 

Thank you again for the explanation.
