### ISSUE TITLE
[YouTube JS Engine Tamer] About Dialog doesn't to show Contents

### ISSUE THREAD

**Issue by TrickyClock** [cyfung1031/userscript-supports#20]
When trying to view channel's about dialog, only the header of the dialog appears.

![about dialog bug](https://github.com/cyfung1031/userscript-supports/assets/116020485/f0a49b4f-ef17-4b5d-9347-e19950d6e7db)

Setting `ENABLE_discreteTasking` to false seems to fix the issue.

---

Reproduction Steps:
1. Go to an about page of any YouTube channel.
2. Click the Tag Line (`channel-tagline`) to display the dialog

Issue 1. YouTube JS Engine Tamer makes content disappear.
Issue 2. YouTube EXPERIMENT_FLAGS Tamer makes no dialog by clicking the tagline.

**Comment by TrickyClock** [comment]
YouTube EXPERIMENT_FLAGS Tamer makes the tagline not show the about dialog, but the more links text works.

**Comment by cyfung1031** [comment]
1. I have just updated the script. Please try again with the latest version.
2. Give me clear steps to reproduce the issue.

**Comment by cyfung1031** [comment]
Fixed. Please check.

**Comment by TrickyClock** [comment]
Works as expected.
