### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by YolandaMorgan** [cyfung1031/userscript-supports#25]
Leetcode部分题目模板代码复制时出现复制不完整的情况： 如https://leetcode.cn/problems/implement-queue-using-stacks/
还原到默认的代码模板后，复制，粘贴时变成

class MyQueue {
public:
    MyQueue() {

    }

    void push(int x) {

    }

… */
后半部分内容丢失且变成"..."

**Comment by cyfung1031** [comment]
已排除 Leetcode。請更新
