### ISSUE TITLE
YouTube EXPERIMENT_FLAGS Tamer breaks video settings icons.

### ISSUE THREAD

**Issue by ChromiaCat** [cyfung1031/userscript-supports#27]
Specifically it's the KEEP_MIDDLEWAVE constant that when it's set most of the icons in the video settings menu disappear.
Setting it to false doesn't do anything, the line that sets it to true has to be commented out.

KEEP_MIDDLEWAVE uncommented:
![image](https://github.com/cyfung1031/userscript-supports/assets/43613021/22ad7181-5658-477e-a6a8-72e9ae85bf96)
KEEP_MIDDLEWAVE commented out:
![image](https://github.com/cyfung1031/userscript-supports/assets/43613021/7d96bc0a-e04f-4229-8225-49e8c6c6564f)

It also seems to rename Ambient Mode to Cinematic Lighting and remove Annotations toggle.

**Comment by cyfung1031** [comment]
Would `const KEEP_MIDDLEWAVE = false;` work for you too?

**Comment by cyfung1031** [comment]
Fixed in 1.3.25!

**Comment by cyfung1031** [comment]
@ChromiaCat Could we close this issue?

**Comment by ChromiaCat** [comment]
> @ChromiaCat Could we close this issue?

Sure thing, thanks for fixing it <3.
