### ISSUE TITLE
Restore YouTube Username from Handle to Custom: Display username if user has no name

### ISSUE THREAD

**Issue by Goosegit11** [cyfung1031/userscript-supports#33]
By default the script doesn't display anything if the person doesn't have a name, this is very inconvenient in comment sections, you can't know who is replying to whom, see example:

![image](https://github.com/cyfung1031/userscript-supports/assets/89806596/74e02e0c-c063-413e-893c-3659db06564a)

So I'd rather fallback to the username instead of just showing nothing.

I see that there is "Support for [NO NAME](https://www.youtube.com/channel/UCXiZNzOwJ-NIwqNkovCBrSg/) ([EXAMPLE](https://www.youtube.com/watch?v=sZlslLuBlOc&lc=UgzXmo4cKhXqTxlffH14AaABAg))" in script's description, so this behavior is intended and you probably don't want to change the default to username fallback.

Then, could you please help me how I can modify the script to achieve this?
Even better would be introducing some kind of options.

**Comment by cyfung1031** [comment]
Your saying is correct, but fallback to the `@user-xxxxx` will be inconsistent with other names. 

Actually this would not affect the function of the script, and "@" with color is still differentiable.
BTW, this is a rare case. Just some users want to play with this. And this script is to restore the previous custom name. This "@" matches the purpose of the script.

I don't have time to do anything with this. Sorry.
