### ISSUE TITLE
[YouTube EXPERIMENT_FLAGS Tamer Script] New flag destroying chat

### ISSUE THREAD

**Issue by NeloBlivion** [cyfung1031/userscript-supports#34]
Yesterday it seems some flag triggered on my account that completely breaks the live chat, creating an even worse memory leak that crashes the entire YouTube frame (even when embeded on mobile), but It only happens on my main and goes away if i switch channels. I found this script and while the full version didn't fix much, the [basic](https://greasyfork.org/en/scripts/473685-youtube-experiment-flags-tamer-basic) variant removed the issue. Just two questions on this:
- Would you be able to identify what flag is causing this new issue?
- This script completely removes the emoji picker and autocomplete; I tried to debug myself with no luck, so would you perhaps know which flag is responsible for these?

Thank you for maintaining these, It's been really helpful!

**Comment by cyfung1031** [comment]
> * Would you be able to identify what flag is causing this new issue?


I could not but you might.


You might figure out by yourself.

As basic variant works for you, start with that.


```js
    const setFalseFn = (EXPERIMENT_FLAGS) => {


      for (const [key, value] of Object.entries(EXPERIMENT_FLAGS)) {


        if (value === true) {

          // ......


        }

      }
    }
```



The basic variant set all the flags from true to false.
You can use the flag name length, contains some words or characters, etc, to filter out those flags.

Trial and Error should let you find the flags that 
* causing memory leakage
* causing the removal of emoji picker and autocomplete.

**Comment by cyfung1031** [comment]
Updated both scripts to whitelist the following.

```
    'disable_features_for_supex'
    'export_networkless_options'
    'suppress_error_204_logging'
    'use_request_time_ms_header'

    'disable_features_for_supex'
    'live_chat_channel_activity'
    'live_chat_web_input_update'


    'remove_masthead_channel_banner_on_refresh'
    'ytidb_fetch_datasync_ids_for_data_cleanup'

    'action_companion_center_align_description',
    'disable_child_node_auto_formatted_strings',
    'enable_native_bridge_view_saved_playables',
    'enable_shadydom_free_scoped_query_methods',
    'enable_skippable_ads_for_unplugged_ad_pod',
    'enable_sparkles_web_clickable_description',
    'enable_window_constrained_buy_flow_dialog',
    'html5_enable_ads_client_monitoring_log_tv',
    'is_part_of_any_user_engagement_experiment',
    'live_chat_enable_send_button_in_slow_mode',
    'live_chat_web_use_emoji_manager_singleton',
    'remove_masthead_channel_banner_on_refresh',
    'web_deprecate_service_ajax_map_dependency',
    'web_modern_player_settings_quality_bottom',
    'web_player_always_enable_auto_translation',
    'web_player_enable_cultural_moment_overlay',
    'ytidb_fetch_datasync_ids_for_data_cleanup',
    'kevlar_tuner_should_test_reuse_components',


    'web_player_ve_conversion_fixes_for_channel_info',
    'web_watch_updated_metadata_server_initial_delay',

    'defer_menus'
    'use_core_sm',
    'use_new_cml',
    'web_api_url',
```

**Comment by NeloBlivion** [comment]
Thank you for the update!! I was making some progress but these flags resolved everything for me 🫡

**Comment by cyfung1031** [comment]
Both Basic version and normal version works for you?

**Comment by NeloBlivion** [comment]
They do, yes (there's a minor issue where a flag happens to interfere with ad blocking and pops up old style instant-skip ads, but that's a separate issue and circumvented by scoping the script to `live_chat` urls)

**Comment by cyfung1031** [comment]
> They do, yes (there's a minor issue where a disabled flag happens to interfere with ad blocking and pops up old style instant-skip ads, but that's a separate issue and circumvented by scoping the script to `live_chat` urls)

If you know the flag for the interfering with ad blocking (trial and error), please let me know.
https://github.com/cyfung1031/userscript-supports/issues/28
I heard that issue but I cannot reproduce it from my side.

**Comment by cyfung1031** [comment]
@NeloBlivion  Might I ask you help testing the following.

https://greasyfork.org/en/scripts/469878-youtube-super-fast-chat

I added the flag disabling option, so YouTube EXPERIMENT_FLAGS Tamer is not required for solving the memory leakage issue.

Could you please try to disable YouTube EXPERIMENT_FLAGS Tamer and enable the YouTube Super Fast Chat to see whether the issue can be solved too?

**Comment by NeloBlivion** [comment]
I've been testing and it seems this works without needing the tamer scripts 👍 thanks!

**Comment by TheAGames10** [comment]
It is April 20th of 2025, I have just tried installing the Super Fast Chat userscript, but it's not working at all, i'm using Tampermonkey on Opera GX and have the userscript enabled.

'YouTube EXPERIMENT_FLAGS Tamer (Basic)' is the only thing working at all on YouTube, but I feel like using Super Fast Chat would be better in some form if these two do work at all to fix the memory leak and crash as well as the YT live chat trying to load in but is blank for a minute or two.
