### ISSUE TITLE
The extension doesn't work today (Restore YouTube Username from Handle to Custom)

### ISSUE THREAD

**Issue by mrkrabs206** [cyfung1031/userscript-supports#36]
I don't know why, but Restore YouTube Username from Handle to Custom stopped working on normal sessions.

Like this:

![bullshphoto](https://github.com/cyfung1031/userscript-supports/assets/110676833/a6e0a670-3cfd-48e8-8579-82fb3c769313)

Possibly something happened and well, it doesn't work.
Even on incognito stopped working.

I removed, restarted and even reinstalled it. Nothing happens.

Even restarted PC. Still nothing.

Is there any explanation and how to fix this problem? Thank you.

**Comment by cyfung1031** [comment]
> Is there any explanation and how to fix this problem? Thank you.

YouTube is always updating its coding. This is normal as they are doing A/B testing everyday.

Login / Logout your account, or just use another browser.

I cannot reproduce it right now. Nothing I can do.

**Comment by cyfung1031** [comment]
I have just fixed an issue due to new youtube coding. Try to update to see if it works for you or not.

**Comment by mrkrabs206** [comment]
> I have just fixed an issue due to new youtube coding. Try to update to see if it works for you or not.

It works now
