### ISSUE TITLE
Adblock Settings

### ISSUE THREAD

**Issue by cyfung1031** [cyfung1031/userscript-supports#37]
1. Whitelist youtube.com in uBO (optional)
2. [YouTubeVideo&music&kidsAdBlocking](https://github.com/cyfung1031/userscript-supports/raw/main/tmp-480192.user.js)
3. [YouTube EXPERIMENT_FLAGS Tamer](https://github.com/cyfung1031/userscript-supports/raw/main/470428.user.js)
4. [YouTube: Stable Streaming](https://greasyfork.org/en/scripts/492004-youtube-stable-streaming)

**Comment by ChromiaCat** [comment]
What does the stable streaming script do?

**Comment by cyfung1031** [comment]
> What does the stable streaming script do?

I guess some ads flags are related to the livestreaming. When ads are not found, the video might get disconnected.
If there are already adblocking, these flags should be turned on to make the live stream become stable.
