### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by SynapseScribe** [cyfung1031/userscript-supports#4]
i still get popup "Video paused. Continue watching?"

the tab was not focused after the video in the playlist ended, could this be the reason?

running Disable YouTube AutoPause v2022.12.28.1 on violent monkey on latest brave

**Comment by cyfung1031** [comment]
Can you please check in DevTools that whether there are log messages like
"YouTube is trying to pause video..."
or
"YouTube is trying to change value 'playbackPauseDelayMs' from XXX to XXX ..."

**Comment by cyfung1031** [comment]
It is intended for background tabs. It shall works.

I just make some coding changes. See if it works for you or not.
If not working, try to open DevTools to get a screen capture of the console log messages

**Comment by cyfung1031** [comment]
I have tried that the current version is able to prevent auto pause.
If there is no further response on this issue, it will be closed.
