### ISSUE TITLE
Korean handles are not converted to usernames.

### ISSUE THREAD

**Issue by wiful10** [cyfung1031/userscript-supports#44]
![555](https://github.com/cyfung1031/userscript-supports/assets/102317996/b3cbc619-56b3-4ceb-9f85-65a9fd2a96e1)

![5555](https://github.com/cyfung1031/userscript-supports/assets/102317996/4ddc59c0-4ad3-4627-8e6b-ec6379222839)

For example, in the case of a user whose user name is ‘하늘’ and whose handle is ‘@김태래’, it is not converted and is displayed as a handle.

![22](https://github.com/cyfung1031/userscript-supports/assets/102317996/646d329e-9100-48fb-92ee-4fcd76bd694a)

**Comment by cyfung1031** [comment]
It is confirmed that this is the update in May~June 2024.
The script will be updated. Please wait.

**Comment by cyfung1031** [comment]
Updated.

**Comment by wiful10** [comment]
It works fine. thank you!
