### ISSUE TITLE
Unhold Youtube Resource Lock does not work

### ISSUE THREAD

**Issue by KohGeek** [cyfung1031/userscript-supports#5]
![image](https://user-images.githubusercontent.com/6839340/210805639-ad429a33-e694-45ce-8a3e-9f9d51e2fdd0.png)

After installing the script, IndexDBs is still locked. Please advice.
I have other inactive youtube tab (force discarded)

**Comment by cyfung1031** [comment]
Wait 1 minute and see whether it is still holding indexedDB lock or not.

**Comment by cyfung1031** [comment]
Does it work for you?
If no further response, this will be closed within a week.

**Comment by KohGeek** [comment]
Hi, using ViolentMonkey on Edge v109, this currently still does not work

**Comment by cyfung1031** [comment]
> Hi, using ViolentMonkey on Edge v109, this currently still does not work

I tried ViolentMonkey and have found the issue. The issue is now fixed. Please update.

**Comment by KohGeek** [comment]
Thank you, it's working now!
