### ISSUE TITLE
youtube music audio only not working

### ISSUE THREAD

**Issue by ThaUnknown** [cyfung1031/userscript-supports#51]
seems like youtube music audio only broke a few days back, unforunate, it seems trustedscript related

**Comment by ThaUnknown** [comment]
fix is 1:1 the same as https://github.com/cyfung1031/userscript-supports/commit/587010b20ee44aa24571cfb749023ab039a65674

manually adding the code solved the problem

**Comment by cyfung1031** [comment]
Yes. This has to be added. To be done

**Comment by cyfung1031** [comment]
fixed now. please  check.

**Comment by ThaUnknown** [comment]
https://github.com/cyfung1031/userscript-supports/commit/f52e0a6040efc4ba80c749b543f058dc5464a7d6
