### ISSUE TITLE
[Issue]Sponsor Block doesn't work with Youtube Audio Only

### ISSUE THREAD

**Issue by olivertzeng** [cyfung1031/userscript-supports#53]
![螢幕截圖_20240824_100936](https://github.com/user-attachments/assets/97ca4458-7550-4bd1-87e4-563ebfacaf63)

**Comment by cyfung1031** [comment]
Youtube Audio Only is a complicated script for just a simple feature. It would make many incompatibilities to other scripts.
You can ask other scripts to fix the conflict. I can do little to fix in my Youtube Audio Only script.

**Comment by olivertzeng** [comment]
> Youtube Audio Only is a complicated script for just a simple feature. It would make many incompatibilities to other scripts.
> 
> You can ask other scripts to fix the conflict. I can do little to fix in my Youtube Audio Only script.

SponsorBlock is a really big addon though 
It's not a script and after testing I figured out that this script is the culprit
SponsorBlock basically automatically skips sponsor and non-music segments submitted by users
