### ISSUE TITLE
[YouTube: Audio Only] [BUG] Thumbnail isn't updated when in fullscreen

### ISSUE THREAD

**Issue by olivertzeng** [cyfung1031/userscript-supports#54]
To reproduce: https://imgur.com/a/jz8bwes

**Comment by cyfung1031** [comment]
Please test by enabling and disabling the scripts/extensions one by one to find which script/extension caused this issue.

**Comment by cyfung1031** [comment]
And sorry I am not quite understand how did you reproduce the issue.
Why the video suddenly changes before entering full screen?

**Comment by olivertzeng** [comment]
> And sorry I am not quite understand how did you reproduce the issue.
> 
> Why the video suddenly changes before entering full screen?

I was using my earphones' gestures to play the next song in the playlist, which replicates the daily use of music playing in a playlist.

**Comment by olivertzeng** [comment]
> Please test by enabling and disabling the scripts/extensions one by one to find which script/extension caused this issue.

I've already done that

Reproduction of the issue only presents when I enable your script

**Comment by olivertzeng** [comment]
> Please test by enabling and disabling the scripts/extensions one by one to find which script/extension caused this issue.

I've already done that

Reproduction of the issue only presents when I enable your script

**Comment by cyfung1031** [comment]
Please name the script. I don't know which script you are talking about.

**Comment by olivertzeng** [comment]
> Please name the script. I don't know which script you are talking about.

Sorry that I didn’t specify, didn’t know that there EE multiple different scripts in this repo. I’m indicating the YouTube audio only script.

**Comment by cyfung1031** [comment]
>  I’m indicating the YouTube audio only script.

I see. I think such a bug is common. The script is doing a forced audio function in YouTube Layout. Its UI is not designed for that. I don't have idea to fix this currently.

**Comment by cyfung1031** [comment]
@olivertzeng  good news. I have located the bug and fixed. please check.

**Comment by olivertzeng** [comment]
> @olivertzeng  good news. I have located the bug and fixed. please check.

Will do! Thanks

**Comment by olivertzeng** [comment]
> @olivertzeng good news. I have located the bug and fixed. please check.

it did work! Thanks a bunch
