### ISSUE TITLE
[Selection and Copying Restorer]Can a switch be added to achieve a function similar to "select-text-inside-a-link-like-opera"?

### ISSUE THREAD

**Issue by 921j** [cyfung1031/userscript-supports#55]
Like the script in the URL below, but with drag and drop instead of selection?
https://github.com/eight04/select-text-inside-a-link-like-opera#readme
This script has not been maintained for a long time and is invalid on most websites.
Thanks!

**Comment by cyfung1031** [comment]
I don't understand what you want. Just hold Alt to select the text.

**Comment by 921j** [comment]
In short, can you provide an option to the script that, when activated, reverses the behavior of holding down the ALT key?
Not press ALT: select text.
Holding ALT: Original behavior.

**Comment by cyfung1031** [comment]
No. Alt to select the text is the browser core feature.

**Comment by 921j** [comment]
The following script can do it, but this script has stopped maintenance for a long time. You can try it. It still works on some sites!
https://github.com/lkytal/GM/raw/master/select.user.js

**Comment by cyfung1031** [comment]
> The following script can do it, but this script has stopped maintenance for a long time. You can try it. It still works on some sites! https://github.com/lkytal/GM/raw/master/select.user.js
> 
> https://greasyfork.org/en/scripts/789-select-text-inside-a-link-like-opera

I just tried. It works. Just sometimes buggy. Select few more times should be fine.

That script is completely different with mine. You are asking me to take over his script. I don't have such a time and I am not interested in this feature. Sorry.
