### ISSUE TITLE
youtube-video-resize-fix: Slowdown when clicking the Player bar to scrub to another timestamp

### ISSUE THREAD

**Issue by davicr** [cyfung1031/userscript-supports#6]
With `youtube-video-resize-fix` enabled, I get prolonged style recalculations when going to another timestamp in a video by clicking on the Player bar. I can reproduce this consistently by recording Performance in Chrome's Developer Tools.

**Comment by cyfung1031** [comment]
Is this problem also occur when only `youtube-video-resize-fix` is enabled?
What is your browser and system OS?

**Comment by cyfung1031** [comment]
>  when going to another timestamp in a video by clicking on the Player bar

This should not trigger any resize of the video player. The correct behaviour should have no style recalculation.

**Comment by cyfung1031** [comment]
Closed due to no further discussion for more than 1 month.
