### ISSUE TITLE
🔴 Suggestions for YouTube CSS Styles

### ISSUE THREAD

**Issue by Thomas-Harrell** [cyfung1031/userscript-supports#61]
---

- Hello CY Fung.

- I am a big fan of your JavaScript scripts and CSS styles.

- I have some suggestions regarding a YouTube CSS style.

- There is a [YouTube CSS style](https://userstyles.world/style/6944/old-youtube-layout-in-2021-2022) developed by [Sapondanai Sriwan](https://github.com/sapondanaisriwan), but it has now ceased basic development.

- As YouTube’s website style continues to update, more and more bugs have appeared in this CSS style.

- I was wondering if you might be able to maintain and upgrade some of the functional modules in this project?

- I have tried to read the code, but my programming skills are limited.

- Only the features under "Video Appearance" are needed.

- This would allow multi-column sorting on pages like the YouTube homepage, search results, channel pages, channel search pages, and channel playlist pages.

- This feature can maximize the use of the horizontal space of the screen, you can make multiple pages of video horizontal multi-column layout, and support custom changes to the number of columns in each row, can greatly enhance the YouTube browsing experience!

- I noticed that you also contributed to another [project](https://github.com/sapondanaisriwan/youtube-row-fixer?tab=readme-ov-file#%EF%B8%8F-credit) by Sapondanai Sriwan.

- Lastly, I hope this request doesn’t trouble you.

- ☕ ☕ ☕

---

**Comment by cyfung1031** [comment]
I think Sapondanai Sriwan is still active in his development. Have you tried to contact him?

**Comment by cyfung1031** [comment]
Oh I see.
I don't have such a time to get involve to that project. 
Sorry.
