### ISSUE TITLE
轉換時，導致留言亂碼

### ISSUE THREAD

**Issue by leadra** [cyfung1031/userscript-supports#64]
目前看是特例而已，能看到轉換前有留言正常中文字
https://www.youtube.com/watch?v=e4Tlz2Gksws
![ZZ01](https://github.com/user-attachments/assets/8fde57d5-fdea-45e3-9453-6b860e5331f0)
大概在三分之二處的留言

**Comment by cyfung1031** [comment]
?? 這是哪個腳本的問題

**Comment by leadra** [comment]
抱歉，習慣了在gresfork了
https://greasyfork.org/zh-TW/scripts/468740
Restore YouTube Username from Handle to Custom

**Comment by cyfung1031** [comment]
感謝回報，日後修正
#65
