### ISSUE TITLE
Feature request: disable auto-pause on music.youtube.com

### ISSUE THREAD

**Issue by maye9999** [cyfung1031/userscript-supports#7]
Hi, I found that auto-pause on music.youtube.com could be annoying. Could you please support the disable auto-pause feature on that domain?  Simply adding the domain to this plugin's support list doesn't work. Maybe they are using different mechanisms?  Thanks in advance.

**Comment by cyfung1031** [comment]
Can you told me how to reproduce the music automatic pause? Just open the browser and play for few hours? Or the browser window has to be minimized? 

Tell me all the relevant scenarios that it might pause.

I am not sure I can make such userscript or not,  coz I did not experience that before in YouTube Music.

**Comment by maye9999** [comment]
> Can you told me how to reproduce the music automatic pause? Just open the browser and play for few hours? Or the browser window has to be minimized?
> 
> Tell me all the relevant scenarios that it might pause.
> 
> I am not sure I can make such userscript or not, coz I did not experience that before in YouTube Music.

Hi, you could just play it in one tab and continue doing your jobs in other tabs. Sometimes it just pauses. I don't know the specific mechanism of it

**Comment by maye9999** [comment]
Great thanks! I'll reopen this issue if not working.
